<a href="https://colab.research.google.com/github/gfgullo/AVSpeechSynthesizer-Example/blob/master/1%20-%20Le%20Basi%20di%20Tensorflow/mi_bocciano.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Un'esempio di Classificazione

In [0]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd

In [4]:
csv_url = "https://raw.githubusercontent.com/ProfAI/tf00/master/1%20-%20Le%20Basi%20di%20Tensorflow/students.csv"
df = pd.read_csv(csv_url, sep=)
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [15]:
df_sub = df[["studytime", "failures", "absences"]]
df_sub["promosso"] = df["G3"]>=10

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [0]:
X = df_sub.drop("promosso", axis=1).values
y = df_sub[["promosso"]].values

In [0]:
model = keras.models.Sequential([
    keras.layers.Dense(1, input_shape=[3], activation="sigmoid")
])

In [0]:
model.compile(optimizer="sgd", loss="binary_crossentropy", metrics=["accuracy"])

In [24]:
model.fit(X, y, epochs=100)

Epoch 1/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5906 - accuracy: 0.7139
Epoch 2/500
13/13 [==============================] - 0s 2ms/step - loss: 0.5888 - accuracy: 0.7114
Epoch 3/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5838 - accuracy: 0.7114
Epoch 4/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5840 - accuracy: 0.7139
Epoch 5/500
13/13 [==============================] - 0s 2ms/step - loss: 0.5833 - accuracy: 0.7139
Epoch 6/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5838 - accuracy: 0.7190
Epoch 7/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5837 - accuracy: 0.7139
Epoch 8/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5857 - accuracy: 0.7063
Epoch 9/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5874 - accuracy: 0.7063
Epoch 10/500
13/13 [==============================] - 0s 1ms/step - loss: 0.5824 - accuracy: 0.7190
Epoch 11/

In [28]:
X_test = [[0, 3, 10], [6, 0, 2], [2, 1, 5]]
model.predict(X_test)

array([[0.14510502],
       [0.82532495],
       [0.5615979 ]], dtype=float32)

In [29]:
model.predict_classes(X_test)

array([[0],
       [1],
       [1]], dtype=int32)

In [30]:
model.weights

[<tf.Variable 'dense_1/kernel:0' shape=(3, 1) dtype=float32, numpy=
 array([[ 0.10021758],
        [-0.9405558 ],
        [ 0.01207529]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.9273937], dtype=float32)>]